# Generated by Django 4.2.8 on 2026-01-29 23:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('combat', 'Combat'), ('exploration', 'Exploration'), ('social', 'Social'), ('learning', 'Learning'), ('challenge', 'Challenge')], max_length=20)),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('requirement_type', models.CharField(max_length=50)),
                ('requirement_value', models.IntegerField()),
                ('xp_reward', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accomplissement',
                'verbose_name_plural': 'Accomplissements',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('study', 'Study Session'), ('quiz', 'Quiz Completed'), ('project', 'Project Submission'), ('comment', 'Community Comment'), ('help', 'Help Given'), ('streak', 'Study Streak'), ('quotidien', 'Activité Quotidienne'), ('day_validated', 'Journée Validée'), ('ia_evaluation', 'Évaluation IA'), ('time_block', 'Time Block'), ('time_block_toggled', 'Time Block Toggled'), ('evaluation_confirmed', 'Evaluation Confirmed'), ('challenge', 'Challenge')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('book', 'Livre'), ('article', 'Article Académique'), ('project', 'Projet'), ('course', 'Cours en Ligne'), ('contribution', 'Contribution Sociale'), ('event', 'Événement Réseau')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Artefact d'Activité",
                'verbose_name_plural': "Artefacts d'Activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_valid', models.BooleanField(default=True)),
                ('xp_awarded', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quality_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_feedback', models.TextField()),
                ('books_read', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('academic_articles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('projects_worked', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('online_courses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('social_contributions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('networking_events', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Évaluation d'Activité",
                'verbose_name_plural': "Évaluations d'Activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], max_length=20)),
                ('challenge_type', models.CharField(max_length=50)),
                ('target_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('xp_reward', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Défi',
                'verbose_name_plural': 'Défis',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationTraitLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_awarded', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('relevance', models.TextField()),
            ],
            options={
                'verbose_name': 'Lien Évaluation-Trait',
                'verbose_name_plural': 'Liens Évaluation-Traits',
            },
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('cognitive', 'Cognitif'), ('emotional', 'Émotionnel'), ('behavioral', 'Comportemental'), ('social', 'Social'), ('moral', 'Moral/Éthique'), ('dark', 'Traits Sombres'), ('motivational', 'Motivationnel'), ('existential', 'Existentiel'), ('leadership', 'Leadership'), ('affective', 'Affectif')], default='behavioral', max_length=20)),
                ('is_negative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trait de Personnalité',
                'verbose_name_plural': 'Traits de Personnalité',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=50)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mastery_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_users', to='gamification.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compétence Utilisateur',
                'verbose_name_plural': 'Compétences Utilisateurs',
                'ordering': ['-experience'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('experience_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('badges_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/images/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profiles/covers/')),
                ('acquired_skills', models.JSONField(blank=True, default=list)),
                ('discovered_categories', models.JSONField(blank=True, default=list)),
                ('explored_domains', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
                'ordering': ['-experience_points'],
            },
        ),
        migrations.CreateModel(
            name='UserPersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_user_stats', to='gamification.personalitytrait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_personality_traits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trait de Personnalité Utilisateur',
                'verbose_name_plural': 'Traits de Personnalité Utilisateurs',
                'ordering': ['-hp'],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_users_challenges', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Défi Utilisateur',
                'verbose_name_plural': 'Défis Utilisateurs',
                'ordering': ['-challenge__start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_users', to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_achievements_unlocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accomplissement Utilisateur',
                'verbose_name_plural': 'Accomplissements Utilisateurs',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('points_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamification_study_sessions', to='gamification.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'Étude",
                'verbose_name_plural': "Sessions d'Étude",
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('auteur', models.CharField(max_length=255, verbose_name='Auteur/Source')),
                ('type', models.CharField(choices=[('Livre', 'Livre'), ('Article', 'Article'), ('FilmSérie', 'Film/Série'), ('Mentor', 'Mentor'), ('Podcast', 'Podcast')], default='Livre', max_length=20, verbose_name='Type')),
                ('domaine', models.CharField(choices=[('Finance', 'Finance'), ('Business', 'Business'), ('Mindset', 'Mindset'), ('Tech', 'Tech'), ('Entrepreneuriat', 'Entrepreneuriat'), ('Philosophie', 'Philosophie'), ('Physique', 'Physique'), ('Chimie', 'Chimie'), ('Agriculture', 'Agriculture'), ('Romans', 'Romans'), ('Autre', 'Autre')], default='Autre', max_length=50, verbose_name='Domaine')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau', models.IntegerField(default=1, help_text='Niveau requis pour accéder (1-1000)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name="Niveau d'accès minimum")),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['niveau', 'domaine'], name='gamificatio_niveau_4a185e_idx'), models.Index(fields=['type'], name='gamificatio_type_85aa7d_idx'), models.Index(fields=['is_active'], name='gamificatio_is_acti_b4e278_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='personalitytrait',
            index=models.Index(fields=['category'], name='gamificatio_categor_409c93_idx'),
        ),
        migrations.AddIndex(
            model_name='personalitytrait',
            index=models.Index(fields=['is_negative'], name='gamificatio_is_nega_b0835c_idx'),
        ),
        migrations.AddField(
            model_name='evaluationtraitlink',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_detected_traits', to='gamification.activityevaluation'),
        ),
        migrations.AddField(
            model_name='evaluationtraitlink',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_evaluations', to='gamification.personalitytrait'),
        ),
        migrations.AddField(
            model_name='activityevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_activity_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityartifact',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_artifacts', to='gamification.activityevaluation'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-experience_points'], name='gamificatio_experie_fb5092_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['level'], name='gamificatio_level_8235fd_idx'),
        ),
        migrations.AddIndex(
            model_name='userpersonalitytrait',
            index=models.Index(fields=['user', '-hp'], name='gamificatio_user_id_0aaee9_idx'),
        ),
        migrations.AddIndex(
            model_name='userpersonalitytrait',
            index=models.Index(fields=['trait'], name='gamificatio_trait_i_d0e41a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpersonalitytrait',
            unique_together={('user', 'trait')},
        ),
        migrations.AlterUniqueTogether(
            name='userchallenge',
            unique_together={('user', 'challenge')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='evaluationtraitlink',
            index=models.Index(fields=['evaluation'], name='gamificatio_evaluat_f5de84_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationtraitlink',
            index=models.Index(fields=['trait'], name='gamificatio_trait_i_8af2f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationtraitlink',
            unique_together={('evaluation', 'trait')},
        ),
        migrations.AddIndex(
            model_name='activityevaluation',
            index=models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_98af26_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevaluation',
            index=models.Index(fields=['-created_at'], name='gamificatio_created_672758_idx'),
        ),
        migrations.AddIndex(
            model_name='activityartifact',
            index=models.Index(fields=['evaluation'], name='gamificatio_evaluat_c9c6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='activityartifact',
            index=models.Index(fields=['artifact_type'], name='gamificatio_artifac_4eb3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_00cec8_idx'),
        ),
    ]
