# Generated by Django 4.2.8 on 2026-01-14 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_valid', models.BooleanField(default=True)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('ai_feedback', models.TextField()),
                ('books_read', models.IntegerField(default=0)),
                ('academic_articles', models.IntegerField(default=0)),
                ('projects_worked', models.IntegerField(default=0)),
                ('online_courses', models.IntegerField(default=0)),
                ('social_contributions', models.IntegerField(default=0)),
                ('networking_events', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_activity_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Évaluation d'Activité",
                'verbose_name_plural': "Évaluations d'Activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trait de Personnalité',
                'verbose_name_plural': 'Traits de Personnalité',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('book', 'Livre'), ('article', 'Article Académique'), ('project', 'Projet'), ('course', 'Cours en Ligne'), ('contribution', 'Contribution Sociale'), ('event', 'Événement Réseau')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_artifacts', to='gamification.activityevaluation')),
            ],
            options={
                'verbose_name': "Artefact d'Activité",
                'verbose_name_plural': "Artefacts d'Activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.personalitytrait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_personality_traits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trait de Personnalité Utilisateur',
                'verbose_name_plural': 'Traits de Personnalité Utilisateurs',
                'ordering': ['-hp'],
                'unique_together': {('user', 'trait')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationTraitLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_awarded', models.IntegerField(default=0)),
                ('relevance', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_detected_traits', to='gamification.activityevaluation')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.personalitytrait')),
            ],
            options={
                'verbose_name': 'Lien Évaluation-Trait',
                'verbose_name_plural': 'Liens Évaluation-Traits',
                'unique_together': {('evaluation', 'trait')},
            },
        ),
        migrations.AddIndex(
            model_name='activityevaluation',
            index=models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_98af26_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevaluation',
            index=models.Index(fields=['-created_at'], name='gamificatio_created_672758_idx'),
        ),
    ]
