# Generated by Django 4.2.8 on 2026-02-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0002_studychapter_studysubject_studysection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cover_images/",
                verbose_name="Image de couverture",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
