# Generated by Django 4.2.8 on 2026-01-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_activityevaluation_personalitytrait_activityartifact_and_more'),
        ('gamification', '0003_load_96_traits'),
    ]

    operations = [
    ]
