# Generated by Django 4.2.8 on 2026-01-15 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_merge_20260115_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalitytrait',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Trait de Personnalité', 'verbose_name_plural': 'Traits de Personnalité'},
        ),
        migrations.AddField(
            model_name='personalitytrait',
            name='category',
            field=models.CharField(choices=[('cognitive', 'Cognitif'), ('emotional', 'Émotionnel'), ('behavioral', 'Comportemental'), ('social', 'Social'), ('moral', 'Moral/Éthique'), ('dark', 'Traits Sombres'), ('motivational', 'Motivationnel'), ('existential', 'Existentiel'), ('leadership', 'Leadership'), ('affective', 'Affectif')], default='behavioral', max_length=20),
        ),
        migrations.AddField(
            model_name='personalitytrait',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activityevaluation',
            name='academic_articles',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activityevaluation',
            name='books_read',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activityevaluation',
            name='networking_events',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activityevaluation',
            name='online_courses',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activityevaluation',
            name='projects_worked',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activityevaluation',
            name='quality_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='activityevaluation',
            name='social_contributions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activityevaluation',
            name='xp_awarded',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='evaluationtraitlink',
            name='hp_awarded',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='evaluationtraitlink',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_evaluations', to='gamification.personalitytrait'),
        ),
        migrations.AlterField(
            model_name='personalitytrait',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userpersonalitytrait',
            name='hp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userpersonalitytrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_user_stats', to='gamification.personalitytrait'),
        ),
        migrations.AddIndex(
            model_name='activityartifact',
            index=models.Index(fields=['evaluation'], name='gamificatio_evaluat_c9c6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='activityartifact',
            index=models.Index(fields=['artifact_type'], name='gamificatio_artifac_4eb3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationtraitlink',
            index=models.Index(fields=['evaluation'], name='gamificatio_evaluat_f5de84_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationtraitlink',
            index=models.Index(fields=['trait'], name='gamificatio_trait_i_8af2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='personalitytrait',
            index=models.Index(fields=['category'], name='gamificatio_categor_409c93_idx'),
        ),
        migrations.AddIndex(
            model_name='personalitytrait',
            index=models.Index(fields=['is_negative'], name='gamificatio_is_nega_b0835c_idx'),
        ),
        migrations.AddIndex(
            model_name='userpersonalitytrait',
            index=models.Index(fields=['user', '-hp'], name='gamificatio_user_id_0aaee9_idx'),
        ),
        migrations.AddIndex(
            model_name='userpersonalitytrait',
            index=models.Index(fields=['trait'], name='gamificatio_trait_i_d0e41a_idx'),
        ),
    ]
