# Generated by Django 4.2.8 on 2026-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_alter_personalitytrait_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('auteur', models.CharField(max_length=255, verbose_name='Auteur/Source')),
                ('type', models.CharField(choices=[('Livre', 'Livre'), ('Article', 'Article'), ('FilmSérie', 'Film/Série'), ('Mentor', 'Mentor'), ('Podcast', 'Podcast')], default='Livre', max_length=20, verbose_name='Type')),
                ('domaine', models.CharField(choices=[('Finance', 'Finance'), ('Business', 'Business'), ('Mindset', 'Mindset'), ('Tech', 'Tech'), ('Entrepreneuriat', 'Entrepreneuriat'), ('Philosophie', 'Philosophie'), ('Physique', 'Physique'), ('Chimie', 'Chimie'), ('Agriculture', 'Agriculture'), ('Romans', 'Romans'), ('Autre', 'Autre')], default='Autre', max_length=50, verbose_name='Domaine')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau', models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3'), (4, 'Niveau 4'), (5, 'Niveau 5'), (6, 'Niveau 6'), (7, 'Niveau 7'), (8, 'Niveau 8'), (9, 'Niveau 9'), (10, 'Niveau 10'), (11, 'Niveau 11'), (12, 'Niveau 12'), (13, 'Niveau 13'), (14, 'Niveau 14'), (15, 'Niveau 15'), (16, 'Niveau 16'), (17, 'Niveau 17'), (18, 'Niveau 18'), (19, 'Niveau 19'), (20, 'Niveau 20'), (21, 'Niveau 21'), (22, 'Niveau 22'), (23, 'Niveau 23'), (24, 'Niveau 24')], default=1, verbose_name="Niveau d'accès")),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['niveau', 'domaine'], name='gamificatio_niveau_4a185e_idx'), models.Index(fields=['type'], name='gamificatio_type_85aa7d_idx'), models.Index(fields=['is_active'], name='gamificatio_is_acti_b4e278_idx')],
            },
        ),
    ]
