# Generated by Django 4.2.8 on 2026-01-16 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='niveau',
            field=models.IntegerField(default=1, help_text='Niveau requis pour accéder (1-1000)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name="Niveau d'accès minimum"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-experience_points'], name='gamificatio_experie_fb5092_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['level'], name='gamificatio_level_8235fd_idx'),
        ),
    ]
