# Generated by Django 4.2.8 on 2026-01-20 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0007_alter_resource_niveau_alter_userprofile_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bedtime', models.TimeField()),
                ('waketime', models.TimeField()),
                ('total_duration_hours', models.FloatField()),
                ('quantity_ratio', models.FloatField()),
                ('quality_ratio', models.FloatField()),
                ('xp_gained', models.IntegerField(default=0)),
                ('hp_gained', models.IntegerField(default=0)),
                ('naps_count', models.IntegerField(default=0)),
                ('total_nap_duration_minutes', models.IntegerField(default=0)),
                ('nap_penalties_xp', models.IntegerField(default=0)),
                ('nap_penalties_hp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_sleeps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sleeps',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SleepNap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('sleep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naps', to='gamification.sleep')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddIndex(
            model_name='sleep',
            index=models.Index(fields=['user', '-date'], name='gamificatio_user_id_ac0ef6_idx'),
        ),
    ]
