# Generated by Django 4.2.8 on 2026-01-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_dailystreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystreak',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sleepnap',
            name='sleep',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='ended_at',
        ),
        migrations.AddField(
            model_name='studysession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('study', 'Study Session'), ('quiz', 'Quiz Completed'), ('project', 'Project Submission'), ('comment', 'Community Comment'), ('help', 'Help Given'), ('streak', 'Study Streak'), ('quotidien', 'Activité Quotidienne'), ('day_validated', 'Journée Validée'), ('ia_evaluation', 'Évaluation IA')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_00cec8_idx'),
        ),
        migrations.DeleteModel(
            name='DailyStreak',
        ),
        migrations.DeleteModel(
            name='Sleep',
        ),
        migrations.DeleteModel(
            name='SleepNap',
        ),
    ]
