# Generated by Django 4.2.8 on 2026-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_remove_dailystreak_user_remove_sleep_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Image de profil'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('study', 'Study Session'), ('quiz', 'Quiz Completed'), ('project', 'Project Submission'), ('comment', 'Community Comment'), ('help', 'Help Given'), ('streak', 'Study Streak'), ('quotidien', 'Activité Quotidienne'), ('day_validated', 'Journée Validée'), ('ia_evaluation', 'Évaluation IA'), ('challenge', 'Challenge'), ('time_block', 'Bloc de Temps'), ('time_block_toggled', 'Bloc de Temps Basculé'), ('evaluation_confirmed', 'Évaluation Confirmée')], max_length=50),
        ),
    ]
