# Generated by Django 4.2.8 on 2026-01-27 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0011_userprofile_cover_image_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Image de couverture du profil', null=True, upload_to='profiles/covers/', verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="Image de profil de l'utilisateur", null=True, upload_to='profiles/images/', verbose_name='Image de profil'),
        ),
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('acquired_skills', models.JSONField(blank=True, default=list)),
                ('discovered_categories', models.JSONField(blank=True, default=list)),
                ('explored_domains', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Game Profiles',
            },
        ),
    ]
