# Generated by Django 4.2.8 on 2026-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0012_alter_userprofile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acquired_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discovered_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='explored_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('study', 'Study Session'), ('quiz', 'Quiz Completed'), ('project', 'Project Submission'), ('comment', 'Community Comment'), ('help', 'Help Given'), ('streak', 'Study Streak'), ('quotidien', 'Activité Quotidienne'), ('day_validated', 'Journée Validée'), ('ia_evaluation', 'Évaluation IA'), ('time_block', 'Time Block'), ('time_block_toggled', 'Time Block Toggled'), ('evaluation_confirmed', 'Evaluation Confirmed'), ('challenge', 'Challenge')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/covers/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/images/'),
        ),
        migrations.DeleteModel(
            name='GameProfile',
        ),
    ]
